import Link from "next/link";
import { ArrowRight, BookOpen, Clock3, Sparkles } from "lucide-react";
import SearchBar from "@/components/search/SearchBar";
import ArticleCard from "@/components/knowledge/ArticleCard";
import CategoryCard from "@/components/knowledge/CategoryCard";
import { mockArticles, mockCategories, recentlyAdded, frequentlyUsed } from "@/data";

export default function Home() {
  const quickGuides = mockArticles.filter((article) => article.category === "quick-guides");
  return <div className="space-y-12">
    <section className="relative overflow-hidden rounded-2xl bg-[#173944] px-6 py-10 text-white md:px-12 md:py-14"><div className="absolute right-0 top-0 h-full w-1/3 bg-[radial-gradient(circle_at_center,#28778233,transparent_65%)]" /><div className="relative max-w-3xl"><div className="mb-5 flex items-center gap-2 text-xs font-bold uppercase tracking-[0.2em] text-[#f1c75b]"><Sparkles size={15} /> Internal knowledge workspace</div><h1 className="text-3xl font-semibold tracking-tight md:text-5xl">Find the SAP process, guide, or solution you need.</h1><p className="mt-4 max-w-xl text-base leading-7 text-[#c6d8db]">MARY GRACE is a demonstration knowledge portal for ERP Support teams.</p><div className="mt-8 max-w-2xl"><SearchBar large /></div><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs text-[#a9c2c6]"><span>Try:</span><Link href="/search?q=PR" className="hover:text-white">Create PR</Link><Link href="/search?q=profit%20center" className="hover:text-white">Profit Center</Link><Link href="/search?q=PID" className="hover:text-white">PID</Link><Link href="/search?q=approved%20PR" className="hover:text-white">Approved PR</Link></div></div></section>
    <section><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow">Explore the library</p><h2 className="section-title">Knowledge categories</h2></div><Link href="/knowledge" className="hidden items-center gap-2 text-sm font-semibold text-[#1e6870] hover:text-[#174e55] sm:flex">View all <ArrowRight size={16} /></Link></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{mockCategories.map((category) => <CategoryCard key={category.slug} category={category} />)}</div></section>
    <section><div className="mb-5 flex items-end justify-between"><div><p className="eyebrow">Recently added</p><h2 className="section-title">Start with a guide</h2></div><Link href="/knowledge" className="flex items-center gap-2 text-sm font-semibold text-[#1e6870] hover:text-[#174e55]">Browse knowledge <ArrowRight size={16} /></Link></div><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{recentlyAdded.map((article) => <ArticleCard key={article.id} article={article} />)}</div></section>
    <section className="grid gap-8 lg:grid-cols-2"><div><div className="mb-5"><p className="eyebrow">Demo content</p><h2 className="section-title">Frequently used guides</h2></div><div className="divide-y divide-[#dbe2e7] rounded-xl border border-[#dbe2e7] bg-white">{frequentlyUsed.map((article) => <Link key={article.id} href={`/articles/${article.slug}`} className="flex items-center justify-between px-5 py-4 transition hover:bg-[#f7faf9]"><span><span className="block text-sm font-semibold">{article.title}</span><span className="mt-1 block text-xs capitalize text-[#71818a]">{article.category.replace("-", " ")} · {article.contentType}</span></span><ArrowRight size={16} className="text-[#9aaab1]" /></Link>)}</div></div><div><div className="mb-5"><p className="eyebrow">Fast reference</p><h2 className="section-title">Quick guides</h2></div><div className="grid gap-3 sm:grid-cols-2">{quickGuides.map((article) => <Link key={article.id} href={`/articles/${article.slug}`} className="flex items-center gap-3 rounded-xl border border-[#dbe2e7] bg-white p-4 text-sm font-semibold transition hover:border-[#8bbec0] hover:shadow-sm"><span className="grid size-9 place-items-center rounded-lg bg-[#fff4cf] text-[#9a7818]"><BookOpen size={17} /></span>{article.title}</Link>)}</div></div></section>
    <div className="flex items-center gap-3 rounded-xl border border-[#dbe2e7] bg-white px-5 py-4 text-sm text-[#687981]"><Clock3 size={17} className="text-[#1e6870]" /><span>Prototype content last refreshed September 21, 2026. All articles are samples for interface testing.</span></div>
  </div>;
}
